const photoBase='https://raw.githubusercontent.com/ClaraFranziska/wo-war-das/main/Fotos/';
const rounds = [{solution:{month:7,year:2017,lat:52.4876,lng:13.4218,place:'Hasenheide 10, Berlin'},photo:`${photoBase}IMG_3564.JPG`},{solution:{month:6,year:2026,lat:52.4887,lng:13.4288,place:'Lenaustraße 10, Berlin'},photo:`${photoBase}image.JPG`},{solution:{month:7,year:2024,lat:42.80593,lng:13.88372,place:'42.80593° N, 13.88372° O'},photo:`${photoBase}IMG_2287.JPG`},{solution:{month:7,year:2026,lat:52.5147,lng:13.2395,place:'Olympiastadion Berlin'},photo:`${photoBase}e47d3fe2-3add-4a13-9565-724239dd4b26.JPG`},{solution:{month:9,year:2024,lat:54.53244,lng:11.07387,place:'54.53244° N, 11.07387° O'},photo:`${photoBase}IMG_3574.JPG`}];
const demoGuesses=[{name:'Anna',team:'Braut',month:7,year:2023,lat:48.99,lng:12.08,points:760},{name:'Felix',team:'Bräutigam',month:10,year:2023,lat:49.2,lng:12.3,points:520},{name:'Sophie',team:'Braut',month:8,year:2023,lat:49.01,lng:12.12,points:980},{name:'Paul',team:'Bräutigam',month:6,year:2023,lat:48.91,lng:11.9,points:410}];
let roundIndex=0;let guessMap;let resultMap;let marker;let chosenPoint=null;let timerId;let seconds=60;
const $=id=>document.getElementById(id);
const months=['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'];
const isHost=new URLSearchParams(window.location.search).has('host');
document.body.classList.toggle('player-mode',!isHost);
$('roomLabel').textContent=isHost?'Beamer · Host-Ansicht':'Demo-Raum';
$('phaseLabel').textContent=`Runde 1 von ${rounds.length}`;
function fillDates(){months.forEach((month,index)=>$('guessMonth').add(new Option(month,index+1)));for(let year=2018;year<=2026;year++)$('guessYear').add(new Option(year,year));$('guessMonth').value=8;$('guessYear').value=2023}
function initMap(){guessMap=L.map('map',{zoomControl:false}).setView([49.05,11.7],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(guessMap);guessMap.on('click',event=>{chosenPoint=event.latlng;if(marker)marker.remove();marker=L.marker(chosenPoint).addTo(guessMap);$('mapHint').textContent='Ort gesetzt. Du kannst ihn noch verschieben.';$('submitGuess').disabled=false})}
function startTimer(){clearInterval(timerId);seconds=60;$('timer').textContent='01:00';timerId=setInterval(()=>{seconds--;const display=`00:${String(seconds).padStart(2,'0')}`;$('timer').textContent=display;if(seconds<=0){clearInterval(timerId);showResults()}},1000)}
function showResults(){clearInterval(timerId);$('guessView').classList.add('hidden');$('gameTitle').textContent='Die Tipps sind da';$('timer').textContent='AUFLÖSUNG';$('resultsView').classList.remove('hidden');renderResults()}
function renderResults(){const solution=rounds[roundIndex].solution;$('solutionTitle').textContent=`${months[solution.month-1]} ${solution.year} · ${solution.place}`;const map=$('resultMap');if(resultMap)resultMap.remove();resultMap=L.map(map,{zoomControl:false}).setView([solution.lat,solution.lng],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(resultMap);L.marker([solution.lat,solution.lng]).addTo(resultMap).bindPopup('Richtiger Ort').openPopup();demoGuesses.forEach(guess=>L.circleMarker([guess.lat,guess.lng],{radius:7,color:guess.team==='Braut'?'#47715c':'#de725f',fillOpacity:.8}).addTo(resultMap));$('timeline').innerHTML=demoGuesses.map(guess=>`<div class="timeline-point ${guess.month===solution.month&&guess.year===solution.year?'correct':''}"><small>${guess.month}/${guess.year}</small><i></i><small>${guess.name}</small></div>`).join('');$('scoreRows').innerHTML=demoGuesses.map(guess=>`<div class="score-row"><span>${guess.name}</span><span>${guess.team}</span><strong>${guess.points}</strong></div>`).join('')}
function startRound(){roundIndex=Math.min(roundIndex+1,rounds.length-1);$('resultsView').classList.add('hidden');$('guessView').classList.remove('hidden');$('phaseLabel').textContent=`Runde ${roundIndex+1} von ${rounds.length}`;$('roundNumber').textContent=roundIndex+1;$('roundPhoto').src=rounds[roundIndex].photo;chosenPoint=null;if(marker){marker.remove();marker=null}$('mapHint').textContent='Tippe auf die Karte, um deinen Ort zu setzen.';$('submitGuess').disabled=true;guessMap.invalidateSize();startTimer()}
$('joinForm').addEventListener('submit',event=>{event.preventDefault();$('joinScreen').classList.add('hidden');$('gameScreen').classList.remove('hidden');fillDates();initMap();startTimer()});$('submitGuess').addEventListener('click',()=>{if(isHost)showResults()});$('nextRound').addEventListener('click',startRound);